export const UNCLASSIFIED_INDUSTRY = '未分类';

const INDUSTRY_BY_SYMBOL: Record<string, string> = {
  'NVDA.US': '半导体',
  'AMD.US': '半导体',
  'AVGO.US': '半导体',
  'INTC.US': '半导体',
  'TSM.US': '半导体',
  'ASX.US': '半导体',
  'AMKR.US': '半导体',
  'SMH.US': '半导体',
  'SOXL.US': '半导体',
  'MU.US': '存储',
  'MUU.US': '存储',
  'SNDK.US': '存储',
  'DISK.US': '存储',
  'DRAM.US': '存储',
  'SKHY.US': '存储',
  'SKHYV.US': '存储',
  'SNK.US': '存储',
  'SNXX.US': '存储',
  'RAM.US': '存储',
  'MRVL.US': '半导体',
  '7709.HK': '存储',
  'AAPL.US': '巨头',
  'MSFT.US': '巨头',
  'GOOG.US': '巨头',
  'GOOGL.US': '巨头',
  'AMZN.US': '巨头',
  'TSLA.US': '巨头',
  'ORCL.US': '软件云',
  'NOW.US': '软件云',
  'NET.US': '软件云',
  'NBIS.US': '软件云',
  'INFQ.US': '软件云',
  'ASTS.US': '航天',
  'RKLB.US': '航天',
  'RKLX.US': '航天',
  'SPCH.US': '航天',
  'SPCX.US': '航天',
  'KO.US': '消费',
  'PEP.US': '消费',
  'MCD.US': '消费',
  'VST.US': '能源电力',
  'QQQM.US': '大盘 ETF',
  'VOO.US': '大盘 ETF',
  'SPY.US': '大盘 ETF',
  'SCHD.US': '大盘 ETF',
  'VXX.US': '波动率',
  'UVIX.US': '波动率',
  'SGOV.US': '现金类',
  'SHV.US': '现金类',
  'USFR.US': '现金类',
  'ICSH.US': '现金类',
  'QCOM.US': '半导体',
  'AEHR.US': '半导体',
  'UMC.US': '半导体',
  'TSEM.US': '半导体',
  'LRCX.US': '半导体',
  'ARM.US': '半导体',
  'MRAM.US': '存储',
  'META.US': '巨头',
  'IBM.US': '软件云',
  'APP.US': '软件云',
  'INTU.US': '软件云',
  'ADBE.US': '软件云',
  'CRWV.US': '软件云',
  'SNOW.US': '软件云',
  'ZETA.US': '软件云',
  'SOUN.US': '软件云',
  'U.US': '软件云',
  'WDAY.US': '软件云',
  'TWLO.US': '软件云',
  'DOCU.US': '软件云',
  'ZM.US': '软件云',
  'CRM.US': '软件云',
  'PLTR.US': '软件云',
  'HSY.US': '消费',
  'AMC.US': '消费',
  'GME.US': '消费',
  'BE.US': '能源电力',
  'HDV.US': '大盘 ETF',
  'VTI.US': '大盘 ETF',
  'QQQ.US': '大盘 ETF',
  'SPCE.US': '航天',
  'CRDO.US': '网络通信',
  'COHR.US': '网络通信',
  'LITE.US': '网络通信',
  'AAOI.US': '网络通信',
  'ANET.US': '网络通信',
  'ALAB.US': '网络通信',
  'CLS.US': '网络通信',
  'GLW.US': '网络通信',
  'HPE.US': '网络通信',
  'SMCI.US': '网络通信',
  'NOK.US': '网络通信',
  'AXTI.US': '网络通信',
  'AMPG.US': '网络通信',
  'OCC.US': '网络通信',
  'UBER.US': '互联网',
  'GRAB.US': '互联网',
  'NFLX.US': '互联网',
  'RDDT.US': '互联网',
  'SHOP.US': '互联网',
  'BMBL.US': '互联网',
  'HOOD.US': '金融',
  'AXS.US': '金融',
  'FNMA.US': '金融',
  'SOFI.US': '金融',
  'NDAQ.US': '金融',
  'BRK.B.US': '金融',
  'PYPL.US': '金融',
  'XYZ.US': '金融',
  'TCEHY.US': '中概股',
  'BILI.US': '中概股',
  'PDD.US': '中概股',
  'BABA.US': '中概股',
  'JD.US': '中概股',
  'TME.US': '中概股',
  'BIDU.US': '中概股',
  'FUTU.US': '中概股',
  'XPEV.US': '中概股',
  'NIO.US': '中概股',
  'MRNA.US': '医疗',
  'TDOC.US': '医疗',
  'HON.US': '工业',
  'AAL.US': '工业',
  'BTDR.US': '加密',
  'MARA.US': '加密',
  'IREN.US': '加密',
  'COIN.US': '加密',
  'URNM.US': '核能铀',
  'CCJ.US': '核能铀',
  'BWXT.US': '核能铀',
  'MP.US': '材料矿业',
  'QUBT.US': '量子计算',
  'SPMO.US': '主题 ETF',
  'EWY.US': '主题 ETF',
  'VGT.US': '主题 ETF',
  'ARKG.US': '主题 ETF',
  'ARKK.US': '主题 ETF',
  'ARKQ.US': '主题 ETF',
  'SOXS.US': '杠杆 ETF',
  'NVDL.US': '杠杆 ETF',
  'GDXU.US': '杠杆 ETF',
  'UCO.US': '杠杆 ETF',
  'TQQQ.US': '杠杆 ETF',
  'SQQQ.US': '杠杆 ETF',
  '5.HK': '金融',
};

export function industryOf(symbol: string): string {
  return INDUSTRY_BY_SYMBOL[symbol] ?? UNCLASSIFIED_INDUSTRY;
}
