import { rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

export interface CliShimInput {
  /** Where the shim goes: <kit>/.kansoku-agent-kit/bin/kansoku-cli. */
  cliShim: string;
  resourcesPath: string;
  platform?: NodeJS.Platform;
  /** The Kansoku executable, which runs the CLI bundle as Node. */
  execPath?: string;
}

const toForwardSlashes = (path: string) => path.replaceAll('\\', '/');

/**
 * Installs the `kansoku-cli` command into the Agent Kit.
 *
 * macOS and Linux link to the packaged shim, which finds the app from its own location.
 * Windows refuses file symlinks without admin rights or Developer Mode, and that shim
 * looks for the macOS app layout anyway, so Windows gets two small launchers with
 * absolute paths instead: one for Git Bash and one (.cmd) for Command Prompt/PowerShell.
 */
export function installCliShim(input: CliShimInput): void {
  const platform = input.platform ?? process.platform;
  if (platform !== 'win32') {
    const target = join(input.resourcesPath, 'kansoku-agent-kit', 'bin', 'kansoku-cli');
    rmSync(input.cliShim, { force: true });
    symlinkSync(target, input.cliShim, 'file');
    return;
  }
  const exe = input.execPath ?? process.execPath;
  const cli = join(input.resourcesPath, 'kansoku-agent-kit', 'cli.js');
  rmSync(input.cliShim, { force: true });
  writeFileSync(
    input.cliShim,
    [
      '#!/bin/sh',
      '# Generated by Kansoku: runs the Agent Kit CLI with the app acting as Node.',
      `ELECTRON_RUN_AS_NODE=1 exec "${toForwardSlashes(exe)}" "${toForwardSlashes(cli)}" "$@"`,
      '',
    ].join('\n'),
    { encoding: 'utf8', mode: 0o755 },
  );
  writeFileSync(
    `${input.cliShim}.cmd`,
    ['@echo off', 'set ELECTRON_RUN_AS_NODE=1', `"${exe}" "${cli}" %*`, ''].join('\r\n'),
    'utf8',
  );
}
